---
title: "measles testbook"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ABSEIR)
library(surveillance)
```

```{r}
# Read in data
data(measlesWeserEms)
# Identify cases
cases<-measlesWeserEms@observed
epidemic.start = min(which(apply(cases, 1, max) > 0))
cases = cases[(epidemic.start-1):nrow(cases),]

# Obtain distance matrix
neighbourhood<-measlesWeserEms@neighbourhood
# Week
week <- measlesWeserEms@epoch[(epidemic.start-1):length(measlesWeserEms@epoch)]
# Vaccination and population data set
vaccine.data <- measlesWeserEms@map@data
vaccine.data$adminID <- rownames(vaccine.data)
# Population size
```


```{r}
N <- vaccine.data$POPULATION



# Check that spatial unit ordering makes sense
if (!all(vaccine.data$adminID == colnames(neighbourhood))){
  stop("Error, make sure spatial unit ordering is consistent.")
}
```

```{r}
# Make cumulative
weser.data_model = DataModel(Y=apply(cases, 2,cumsum), 
                             type = "identity",      # Assume data is correct 
                             compartment = "I_star", # Data related to new infections
                             cumulative = TRUE       # Not reported on cumulative scale
                             )
```

```{r}
I0 = (apply(cases[1:3,], 2, max) > 0)*2
E0 = I0
R0 = 0*I0
S0 = N-E0-I0-R0

weser.initial_values = InitialValueContainer(S0 = S0, 
                                             E0 = E0,
                                             I0 = I0,
                                             R0 = R0)

# No reinfection
weser.reinfection_model = ReinfectionModel("SEIR")
```

```{r}
n.locations <- ncol(neighbourhood)
n.timepoints <- length(week)

time_invariant_covariates <- data.frame(intercept = rep(1, nrow(vaccine.data)),
                                        popDensity = vaccine.data$POPULATION/vaccine.data$AREA,
                                        proportionVaccineCard = vaccine.data$vaccdoc.2004,
                                        proportionVaccine1 = vaccine.data$vacc1.2004,
                                        proportionVaccine2 = vaccine.data$vacc2.2004)

time_varying_covariates <- data.frame(sin_component = sin(week/52*2*pi),
                                      cos_component = cos(week/52*2*pi),
                                      trig_interact = sin(week/52*2*pi)*cos(week/52*2*pi))

exposure.design.matrix <- as.matrix(
                            cbind(
                              time_invariant_covariates[rep(1:n.locations, each = n.timepoints),],
                              time_varying_covariates[rep(1:n.timepoints, n.locations),]
                            )
                          )

## Build the exposure model

weser.exposure_model <- ExposureModel(X = exposure.design.matrix,
                                      nTpt = n.timepoints,
                                      nLoc = n.locations,
                                      betaPriorPrecision = rep(1, ncol(exposure.design.matrix)),
                                      betaPriorMean = rep(0, ncol(exposure.design.matrix)))
```
```{r}
# Build a gravity model, in which the contact process between a pair of
# spatial locations is proportional to the product of their populations divided
# by the squared 'distance'

pop.matrix <- matrix(N, nrow = length(N), ncol = length(N))
gravityModel <- (pop.matrix * t(pop.matrix))/neighbourhood^2
diag(gravityModel) <- 1
# Rescale
maxRowSum <- max(apply(gravityModel,1,sum))
gravityModel <- gravityModel/maxRowSum

weser.distance_model <- DistanceModel(list(gravityModel), 
                                      priorAlpha = 1,
                                      priorBeta = 1)

# Build a simpler contact model, in which the contact probability between
# a pair of spatial locations is only nonzero when the distance is equal to 1
# (CAR specification)
weser.CAR_model <- DistanceModel(list((neighbourhood == 1)*1), 
                                 priorAlpha = 1,
                                 priorBeta = 1
                                 )
```

```{r}
# 9-12 day latent period
# Infectious
weser.transition_priors = ExponentialTransitionPriors(p_ei = 0.8, # Guess at E to I transition probability (per week)
                                                      p_ir = 0.8, # Guess at I to R transition probability (per week)
                                                      p_ei_ess = 10, # confidence
                                                      p_ir_ess = 10  # confidence
                                                      )
```

```{r}
weser.sampling_control <- SamplingControl(seed=123124,
                                               n_cores = 14,
                                               algorithm = "Beaumont2009",
                                               params = list(
                                                  batch_size = 2000,
                                                  init_batch_size = 1000000,
                                                  epochs = 1e6,
                                                  shrinkage = 0.99,
                                                  max_batches = 200,
                                                  multivariate_perturbation=FALSE
                                              ))
```

```{r}
weser.model1 <- SpatialSEIRModel(data_model = weser.data_model,
                                     exposure_model = weser.exposure_model,
                                     reinfection_model = weser.reinfection_model,
                                     distance_model = weser.distance_model,
                                     transition_priors = weser.transition_priors,
                                     initial_value_container = weser.initial_values,
                                     sampling_control = weser.sampling_control,
                                     samples = 50, 
                                     verbose = FALSE)

weser.model2 <- SpatialSEIRModel(data_model = weser.data_model,
                                   exposure_model = weser.exposure_model,
                                   reinfection_model = weser.reinfection_model,
                                   distance_model = weser.CAR_model,
                                   transition_priors = weser.transition_priors,
                                   initial_value_container = weser.initial_values,
                                   sampling_control = weser.sampling_control,
                                   samples = 50,
                                   verbose = 2)
```
```{r}
beta_idx <- grepl("Beta_SE", colnames(weser.model2$param.samples)) # use to get beta estimates/samples
eta <- weser.exposure_model$X[97:192,] %*% t(weser.model2$param.samples[,beta_idx]) # get intensity matrix/time series (X(se) x Beta(se))
 
 plot(apply(eta, 1, mean), 
      type = 'l', 
      main = 'Model 3 Intensity Prediction',
      ylab = 'η',
      xlab = 'Epidemic Day')
 
 # drives the I_star compartment
```








